---
- hosts: localhost
  become: true
  tasks:
  - name: Deploy the Visit Service
    k8s:
      state: present
      definition: "{{ lookup('file', './visit-service-application.yaml') }}"
      validate_certs: no
      kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
      namespace: pilot 