---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-service-deployment
  namespace: pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visit-service
      tier: backend
  template:
    metadata:
      labels:
        app: visit-service
        tier: backend
    spec:
      containers:
      - name: visit-service
        image: nexus.grupogloria.corp:8443/visit-service
        #image: raulramosm/visit-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8007
---
apiVersion: v1
kind: Service
metadata:
  name: visit-service
  namespace: pilot
spec:
  type: LoadBalancer
  selector:
    app: visit-service
    tier: backend 
  ports:
  - port: 33007
    protocol: TCP
    targetPort: 8007